### ISSUE TITLE
set default checked don't working

### ISSUE THREAD

**Issue by gplcn** [msdx/AndroidSnippet#1]
modify your ChoiceListAdapter code but no effect:
public View getView(int position, View convertView, ViewGroup parent) {
        final ChoiceLayout view;
        if (convertView == null) {
            view = new ChoiceLayout(mContext);
            view.setLayoutAndChoiceId(mLayoutId, mChoiceId);
            holdView(view);
        } else {
            view = (ChoiceLayout) convertView;
        }
        bindData(view, position, mData.get(position));
        **if(position==0)
        view.setChecked(true);**
        return view;
    }

**Comment by msdx** [comment]
@gplcn You should use `listview.setItemChecked(position,  true)` to check the item.

**Comment by gplcn** [comment]
yeah, this is right ! thanks
